### ISSUE TITLE
how can i create other users

### ISSUE THREAD

**Issue by francisguchie** [IMS94/chr247.com#15]
The software looks greate. But how can i add new users in the system

**Comment by IMS94** [comment]
Hi @francisguchie,
When you login with the user which you used to register the clinic, click the username on top right corner. The drop down will have a **settings** icon. Click that. Inside that, you can add new users, assign roles and etc. Let me know if you are unable to find that.

**Comment by francisguchie** [comment]
Yes @IMS94  
it is working fine

**Comment by francisguchie** [comment]
Dear Imesha,

Thanks a lot for your help. It is working now very well. I have added
another issue

My Kind Regards

Francis Guchie Kirago
