### ISSUE TITLE
Installation CHR247 on Ubuntu Linux 18.04 LTS

### ISSUE THREAD

**Issue by francisguchie** [IMS94/chr247.com#20]
@IMS94 ,
i installed chr247 on both a windows Machine and a Linux Ubuntu 18.04 Lts server. 

i noticed that the steps provided  here
https://github.com/IMS94/chr247.com/blob/master/readme.md
are for a windows OS. 

I would like to share the steps for installation on Ubuntu 18.04, if you would like

**Comment by francisguchie** [comment]
i can do a PR to that effect

**Comment by IMS94** [comment]
@francisguchie The current installation steps are for an ubuntu based system. Is there anything missing? #18 PR seems to add steps for windows. Couldn't review and merge that yet.

**Comment by pasan93** [comment]
@francisguchie Docker installer is now available.

**Comment by francisguchie** [comment]
@pasan93  this is great news i am going to test it one of these days
